version: "3"

services:

  juwo:
    build: .
    image: ${DOCKER_REPO}:${JUWO_IMAGE_DEV_TAG:-latest-dev}
    ports:
      - "5001:5001"
    environment:
      ENV: DEV 
    # volumes:
    #   - ./koatest:/project/koatest
    depends_on:
      - mongodb
      - redis
      - rabbitmq
  
  mongodb:
    image: mongo:3.4.3
  
  redis:
    image: redis:3.2.8-alpine

  rabbitmq:
    image: rabbitmq:3.6.9-alpine
